import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'

export const dynamic = 'force-dynamic'

/**
 * Generate portfolio wines from proforma data
 * Returns TypeScript code ready to replace data/wines.ts
 */
export async function GET(request: Request) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user || session.user.role !== 'ADMIN') {
      return NextResponse.json(
        { error: 'Forbidden: Admin access required' },
        { status: 403 }
      )
    }

    // Map proforma data to portfolio wine structure
    const proformaWines = [
      // L'AUTIN (Piemonte Alps) - 5 wines
      {
        id: 'l-autin-el-bertu-2021',
        slug: 'l-autin-el-bertu-2021',
        producerId: 'l-autin',
        wineName: 'El Bertu 2021',
        displayName: "L'Autin El Bertu 2021",
        type: 'Red',
        region: 'Piemonte Alps',
        appellation: null,
        vintage: 2021,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 480,
        costEUR: 8.00,
        description:
          'Alpine red from the Piemonte Alps with bright dark cherry and wild violet. Vivid mountain terroir with accessible, crowd-pleasing character.',
      },
      {
        id: 'l-autin-gemma-vitis-bonarda-2025',
        slug: 'l-autin-gemma-vitis-bonarda-2025',
        producerId: 'l-autin',
        wineName: 'Gemma Vitis (Bonarda) 2025',
        displayName: "L'Autin Gemma Vitis Bonarda 2025",
        type: 'Red',
        region: 'Piemonte Alps',
        appellation: null,
        vintage: 2025,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 960,
        costEUR: 5.60,
        description:
          'Lightly frizzante Bonarda from the alpine foothills. Fresh dark cherry, blackberry, and wild violet with vivid effervescence. Perfect for aperitifs.',
      },
      {
        id: 'l-autin-re-nero-pinot-nero-2022',
        slug: 'l-autin-re-nero-pinot-nero-2022',
        producerId: 'l-autin',
        wineName: 'Re Nero (Pinot Nero) 2022',
        displayName: "L'Autin Re Nero Pinot Nero 2022",
        type: 'Red',
        region: 'Piemonte Alps',
        appellation: null,
        vintage: 2022,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 360,
        costEUR: 8.50,
        description:
          'Alpine Pinot Nero with elegant red fruit, mineral undertones, and mountain freshness. Structured yet approachable mountain red wine.',
      },
      {
        id: 'l-autin-le-ramie-2024',
        slug: 'l-autin-le-ramie-2024',
        producerId: 'l-autin',
        wineName: 'Le Ramie (Ramìe) 2024',
        displayName: "L'Autin Le Ramie 2024",
        type: 'Red',
        region: 'Piemonte Alps',
        appellation: null,
        vintage: 2024,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 180,
        costEUR: 12.00,
        description:
          'Premium expression from the alpine estate. Complex aromas with fine tannin structure. Mountain terroir at its finest.',
      },
      {
        id: 'l-autin-musca-bianca-2023',
        slug: 'l-autin-musca-bianca-2023',
        producerId: 'l-autin',
        wineName: 'Musca Bianca 2023',
        displayName: "L'Autin Musca Bianca 2023",
        type: 'White',
        region: 'Piemonte Alps',
        appellation: null,
        vintage: 2023,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 720,
        costEUR: 5.60,
        description:
          'Alpine white with mineral crispness and stone fruit character. Fresh, accessible daily drinker from the mountain region.',
      },

      // LANTIERI (Franciacorta) - 3 wines
      {
        id: 'lantieri-franciacorta-brut',
        slug: 'lantieri-franciacorta-brut',
        producerId: 'lantieri',
        wineName: 'Franciacorta Brut',
        displayName: 'Lantieri Franciacorta Brut',
        type: 'Sparkling',
        region: 'Lombardy',
        appellation: 'Franciacorta DOCG',
        vintage: null,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 960,
        costEUR: 12.50,
        description:
          'Champagne-method sparkling from Lombardy. Toasty brioche, citrus notes, fine persistent bubbles. Celebrates Italian Franciacorta excellence.',
      },
      {
        id: 'lantieri-franciacorta-saten',
        slug: 'lantieri-franciacorta-saten',
        producerId: 'lantieri',
        wineName: 'Franciacorta Satèn',
        displayName: 'Lantieri Franciacorta Satèn',
        type: 'Sparkling',
        region: 'Lombardy',
        appellation: 'Franciacorta DOCG',
        vintage: null,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 480,
        costEUR: 14.20,
        description:
          'Soft, refined Franciacorta with creamy mousse and delicate bubbles. Elegant aperitif and celebration wine with sophisticated presence.',
      },
      {
        id: 'lantieri-franciacorta-rose',
        slug: 'lantieri-franciacorta-rose',
        producerId: 'lantieri',
        wineName: 'Franciacorta Rosé',
        displayName: 'Lantieri Franciacorta Rosé',
        type: 'Sparkling Rosé',
        region: 'Lombardy',
        appellation: 'Franciacorta DOCG',
        vintage: null,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 480,
        costEUR: 14.20,
        description:
          'Pink-tinted Franciacorta with wild strawberry and raspberry. Fine bubbles with dry finish. Perfect for sophisticated moments.',
      },

      // LUCA FACCINELLI (Valtellina) - 3 wines
      {
        id: 'faccinelli-rosso-di-valtellina-2024',
        slug: 'faccinelli-rosso-di-valtellina-2024',
        producerId: 'luca-faccinelli',
        wineName: 'Rosso di Valtellina 2024',
        displayName: 'Luca Faccinelli Rosso di Valtellina 2024',
        type: 'Red',
        region: 'Lombardy',
        appellation: 'Valtellina DOC',
        vintage: 2024,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 600,
        costEUR: 10.40,
        description:
          'Accessible Nebbiolo-based red from alpine Valtellina. Bright acidity, red fruit, food-friendly structure. Summer mountain wine.',
      },
      {
        id: 'faccinelli-grumello-2022',
        slug: 'faccinelli-grumello-2022',
        producerId: 'luca-faccinelli',
        wineName: 'Grumello 2022',
        displayName: 'Luca Faccinelli Grumello 2022',
        type: 'Red',
        region: 'Lombardy',
        appellation: 'Valtellina Superiore DOCG',
        vintage: 2022,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 480,
        costEUR: 15.80,
        description:
          'Premium Valtellina Superiore with structure and complexity. Old vine Nebbiolo with mineral character and aging potential.',
      },
      {
        id: 'faccinelli-grumello-riserva-2021',
        slug: 'faccinelli-grumello-riserva-2021',
        producerId: 'luca-faccinelli',
        wineName: 'Grumello Riserva 2021',
        displayName: 'Luca Faccinelli Grumello Riserva 2021',
        type: 'Red',
        region: 'Lombardy',
        appellation: 'Valtellina Superiore DOCG',
        vintage: 2021,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 120,
        costEUR: 23.50,
        description:
          'Reserve expression of high-altitude Valtellina. Serious structured wine for collectors. Complex, layered, built to cellar.',
      },

      // RANDI (Emilia-Romagna) - Bottled - 3 wines
      {
        id: 'randi-blu-di-burson',
        slug: 'randi-blu-di-burson',
        producerId: 'randi',
        wineName: 'Blu di Burson',
        displayName: 'Randi Blu di Burson',
        type: 'Red',
        region: 'Emilia-Romagna',
        appellation: null,
        vintage: null,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 720,
        costEUR: 5.80,
        description:
          'Organic red blend with dark fruit and earthy character. Fresh, approachable daily drinker from certified organic farming.',
      },
      {
        id: 'randi-burson-selezione',
        slug: 'randi-burson-selezione',
        producerId: 'randi',
        wineName: 'Burson Selezione',
        displayName: 'Randi Burson Selezione',
        type: 'Red',
        region: 'Emilia-Romagna',
        appellation: null,
        vintage: null,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 720,
        costEUR: 8.90,
        description:
          'Premium selection from Randi. Deeper fruit, more structure. Elevated organic red for food pairing.',
      },
      {
        id: 'randi-skin-contact-white',
        slug: 'randi-skin-contact-white',
        producerId: 'randi',
        wineName: 'Skin Contact White',
        displayName: 'Randi Skin Contact White',
        type: 'White',
        region: 'Emilia-Romagna',
        appellation: null,
        vintage: null,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 720,
        costEUR: 6.40,
        description:
          'Natural white wine with extended skin contact. Orange hue, texture, tannin. Modern natural wine approach.',
      },

      // RANDI (Emilia-Romagna) - Cans - 5 products
      {
        id: 'randi-spritz-250ml-can',
        slug: 'randi-spritz-250ml-can',
        producerId: 'randi',
        wineName: 'Spritz 250ml',
        displayName: 'Randi Spritz Canned (250ml)',
        type: 'Red',
        region: 'Emilia-Romagna',
        appellation: null,
        vintage: null,
        format: 'can',
        bottleSizeMl: 250,
        quantity: 7920,
        costEUR: 1.80,
        description:
          'Canned aperitif wine in convenient 250ml format. Perfect for events, on-trade, and casual service. Zero waste.',
      },
      {
        id: 'randi-bianco-187ml-can',
        slug: 'randi-bianco-187ml-can',
        producerId: 'randi',
        wineName: 'Bianco 187ml',
        displayName: 'Randi Bianco Canned (187ml)',
        type: 'White',
        region: 'Emilia-Romagna',
        appellation: null,
        vintage: null,
        format: 'can',
        bottleSizeMl: 187,
        quantity: 2376,
        costEUR: 1.75,
        description:
          'Single-serve canned white wine. 187ml perfect portion for by-the-glass service without waste.',
      },
      {
        id: 'randi-rosso-187ml-can',
        slug: 'randi-rosso-187ml-can',
        producerId: 'randi',
        wineName: 'Rosso 187ml',
        displayName: 'Randi Rosso Canned (187ml)',
        type: 'Red',
        region: 'Emilia-Romagna',
        appellation: null,
        vintage: null,
        format: 'can',
        bottleSizeMl: 187,
        quantity: 2376,
        costEUR: 1.75,
        description:
          'Single-serve canned red wine. Portion-controlled for restaurants and events. Organic certified.',
      },
      {
        id: 'randi-bianco-frizzante-187ml-can',
        slug: 'randi-bianco-frizzante-187ml-can',
        producerId: 'randi',
        wineName: 'Bianco Frizzante',
        displayName: 'Randi Bianco Frizzante Canned (187ml)',
        type: 'Sparkling',
        region: 'Emilia-Romagna',
        appellation: null,
        vintage: null,
        format: 'can',
        bottleSizeMl: 187,
        quantity: 2376,
        costEUR: 1.75,
        description:
          'Fizzy white in handy can. Aperitif option for on-trade service. Organic, practical, festive.',
      },
      {
        id: 'randi-rosato-frizzante-187ml-can',
        slug: 'randi-rosato-frizzante-187ml-can',
        producerId: 'randi',
        wineName: 'Rosato Frizzante',
        displayName: 'Randi Rosato Frizzante Canned (187ml)',
        type: 'Sparkling Rosé',
        region: 'Emilia-Romagna',
        appellation: null,
        vintage: null,
        format: 'can',
        bottleSizeMl: 187,
        quantity: 2376,
        costEUR: 1.75,
        description:
          'Pink sparkling in canned format. Party wine. Zero-waste solution for high-volume service.',
      },

      // STROPPIANA (Barolo) - 4 wines
      {
        id: 'stroppiana-barbera-dalba',
        slug: 'stroppiana-barbera-dalba',
        producerId: 'stroppiana',
        wineName: "Barbera d'Alba",
        displayName: "Stroppiana Barbera d'Alba",
        type: 'Red',
        region: 'Piemonte',
        appellation: "Barbera d'Alba DOC",
        vintage: null,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 480,
        costEUR: 4.50,
        description:
          "Piemonte's everyday red. Bright acidity, ripe dark cherry. Punches above its price point with versatility and food friendliness.",
      },
      {
        id: 'stroppiana-barolo-leonardo',
        slug: 'stroppiana-barolo-leonardo',
        producerId: 'stroppiana',
        wineName: 'Barolo Leonardo',
        displayName: 'Stroppiana Barolo "Leonardo"',
        type: 'Red',
        region: 'Piemonte',
        appellation: 'Barolo DOCG',
        vintage: null,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 960,
        costEUR: 10.50,
        description:
          'Classic Barolo with firm structure, red fruit, and aging potential. Nebbiolo from prestigious Piemonte region.',
      },
      {
        id: 'stroppiana-barolo-bricco-cogni-2019',
        slug: 'stroppiana-barolo-bricco-cogni-2019',
        producerId: 'stroppiana',
        wineName: 'Barolo Bricco Cogni 2019',
        displayName: 'Stroppiana Barolo "Bricco Cogni" 2019',
        type: 'Red',
        region: 'Piemonte',
        appellation: 'Barolo DOCG',
        vintage: 2019,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 420,
        costEUR: 13.00,
        description:
          'Single-vineyard Barolo with terroir complexity. Structured, elegant, worthy of cellaring. Serious collector wine.',
      },
      {
        id: 'stroppiana-barolo-bussia',
        slug: 'stroppiana-barolo-bussia',
        producerId: 'stroppiana',
        wineName: 'Barolo Bussia',
        displayName: 'Stroppiana Barolo "Bussia"',
        type: 'Red',
        region: 'Piemonte',
        appellation: 'Barolo DOCG',
        vintage: null,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 120,
        costEUR: 19.00,
        description:
          'Premium single-vineyard expression. Powerful, complex, built for the cellar. Top-tier Nebbiolo.',
      },

      // ZANOTELLI (Trentino) - 4 wines
      {
        id: 'zanotelli-kerner-2025',
        slug: 'zanotelli-kerner-2025',
        producerId: 'zanotelli',
        wineName: 'Kerner 2025',
        displayName: 'Zanotelli Kerner 2025',
        type: 'White',
        region: 'Trentino-Alto Adige',
        appellation: 'Alto Adige DOC',
        vintage: 2025,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 720,
        costEUR: 7.10,
        description:
          'Alpine white with stone fruit and mineral character. Fresh acidity, accessible, mountain terroir.',
      },
      {
        id: 'zanotelli-lagrein-2025',
        slug: 'zanotelli-lagrein-2025',
        producerId: 'zanotelli',
        wineName: 'Lagrein 2025',
        displayName: 'Zanotelli Lagrein 2025',
        type: 'Red',
        region: 'Trentino-Alto Adige',
        appellation: 'Alto Adige DOC',
        vintage: 2025,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 720,
        costEUR: 7.30,
        description:
          'Native Alpine red with dark cherry and herbal notes. Medium-bodied, mineral, food-friendly.',
      },
      {
        id: 'zanotelli-schiava-2024',
        slug: 'zanotelli-schiava-2024',
        producerId: 'zanotelli',
        wineName: 'Schiava 2024',
        displayName: 'Zanotelli Schiava 2024',
        type: 'Red',
        region: 'Trentino-Alto Adige',
        appellation: 'Alto Adige DOC',
        vintage: 2024,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 720,
        costEUR: 5.95,
        description:
          'Light Alpine red, bright and easy-drinking. Cherry, fresh acidity. Perfect for warm days and casual meals.',
      },
      {
        id: 'zanotelli-riesling-2023',
        slug: 'zanotelli-riesling-2023',
        producerId: 'zanotelli',
        wineName: 'Riesling 2023',
        displayName: 'Zanotelli Riesling 2023',
        type: 'White',
        region: 'Trentino-Alto Adige',
        appellation: 'Alto Adige DOC',
        vintage: 2023,
        format: 'bottle',
        bottleSizeMl: 750,
        quantity: 6,
        costEUR: 0,
        description:
          'Alpine Riesling with stone fruit, floral notes. Crisp acidity, mineral freshness. Serious wine for collectors.',
      },
    ]

    return NextResponse.json(
      {
        message: 'Generated 27 proforma wines for portfolio',
        wineCount: proformaWines.length,
        summary: {
          'L\'Autin': 5,
          Lantieri: 3,
          Faccinelli: 3,
          'Randi (Bottles)': 3,
          'Randi (Cans)': 5,
          Stroppiana: 4,
          Zanotelli: 4,
        },
        wines: proformaWines,
        instructions: [
          '1. Copy the wines array from the response',
          '2. Transform wines to use buildWinePricing() for pricing calculations',
          '3. Update data/wines.ts WINES export',
          '4. Re-run database seeding to populate Product table',
          '5. Verify alignment dashboard shows 27 wines',
        ],
        timestamp: new Date().toISOString(),
      },
      { status: 200 }
    )
  } catch (err) {
    console.error('[portfolio-generator] Error:', err)
    return NextResponse.json(
      {
        error: 'Failed to generate portfolio wines',
        details: err instanceof Error ? err.message : 'Unknown error',
      },
      { status: 500 }
    )
  }
}
